spring:

  # h2 database의 console을 확인할 수 있도록 enabled 설정
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop # SeesionFactory가 시작될 때 Drop, Create, Alter / 종료 시 Drop
    properties:
      hibernate: # Console에서 sql을 확인하기 위한 작업
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true